# Generated by Django 4.1 on 2022-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='descreption',
            field=models.TextField(default=''),
        ),
    ]
