# Generated by Django 4.1 on 2022-08-16 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=600), null=True),
        ),
    ]
